version: '3.8'

services:
  app:
    image: yujik/expo-real-time-monitoring:1.0
    container_name: expo-real-time-monitoring
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./config.json:/app/config.json