version: '3.8'

services:
  app:
    build: .
    container_name: expo-real-time-monitoring
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - .:/app
    
  # 開発用サービス（デバッグモード）
  app-dev:
    build: .
    container_name: expo-real-time-monitoring-dev
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - .:/app
    command: ["node", "index.js", "--debug"]
    profiles:
      - dev