version: '3.8'

services:
  app:
    image: yujik/expo-real-time-monitoring:latest
    container_name: expo-real-time-monitoring
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./config.json:/app/config.json
      - ./availability_log.jsonl:/app/availability_log.jsonl